---
- - :permit
  - MIT
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2017-07-28 11:11:09.971500380 Z
- - :permit
  - Apache 2.0
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2017-07-28 11:12:21.086779416 Z
- - :permit
  - ruby
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2017-07-28 11:12:28.578927478 Z
- - :permit
  - Simplified BSD
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2017-07-28 11:12:36.924605442 Z
- - :permit
  - New BSD
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2017-07-28 11:14:00.252514982 Z
- - :permit
  - Apache License, v2
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2017-07-28 11:14:07.999759997 Z
- - :permit
  - Ruby or LGPLv3+
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2017-07-28 11:18:47.915684798 Z
- - :license
  - bundler
  - MIT
  - :who: DavidS
    :why: See https://rubygems.org/gems/bundler
    :versions: []
    :when: 2017-07-28 11:22:12.975947786 Z
- - :license
  - minitar
  - ruby
  - :who: DavidS
    :why: https://rubygems.org/gems/minitar
    :versions: []
    :when: 2017-07-28 11:22:50.609762862 Z
- - :license
  - colored
  - MIT
  - :who: DavidS
    :why: https://github.com/defunkt/colored/blob/829bde0f8832406be1cacc5c99c49d976e05ccfc/LICENSE
    :versions: []
    :when: 2017-07-28 11:23:25.554994001 Z
- - :permit
  - ISC
  - :who: scotje
    :why: MIT equivalent
    :versions: []
    :when: 2017-08-11 01:30:32.594531000 Z
- - :license
  - facter
  - Apache 2.0
  - :who: rodjek
    :why: https://github.com/puppetlabs/facter/blob/d85f088d74f60859a23e6dbae3f83d918dff504a/LICENSE
    :versions: []
    :when: 2019-04-05 00:51:23.372598896 Z
- - :permit
  - BSD
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2021-03-31 08:27:14.976580116 Z
- - :permit
  - 2-clause BSDL
  - :who: DavidS
    :why: standard license
    :versions: []
    :when: 2021-03-31 08:27:24.951961169 Z
- - :approve
  - log4r
  - :who: DavidS
    :why: 'dug up original source on github, licensed as LGPLv3: https://github.com/colbygk/log4r/tree/40e2c2edd657a21b34f09dec7de238f348b6f428'
    :versions:
    - 1.1.10
    :when: 2021-03-31 08:49:39.015791690 Z
