name: "Acceptance Tests"

on: [pull_request]

env:
  BOLT_GEM: true
  CI: true
  BUNDLE_JOBS: 4
  BUNDLE_WITH: "acceptance_ci"

jobs:
  Acceptance:
    name: 'Acceptance Tests (Ruby ${{ matrix.ruby_version }})'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - provider: docker
            ruby_version: 2.5
            image: ruby:2.5

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2

    - name: Activate Ruby 2.7
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "2.7"
        bundler-cache: true
    
    - name: Provision test environment
      run: |
        bundle exec rake 'litmus:provision[${{ matrix.provider }},${{ matrix.image }}]'
        bundle exec bolt command run "git clone https://github.com/$GITHUB_REPOSITORY pdk" --targets ssh_nodes --inventory inventory.yaml
        bundle exec bolt command run "cd pdk && git checkout $GITHUB_HEAD_REF" --targets ssh_nodes --inventory inventory.yaml
        bundle exec bolt command run 'cd pdk && bundle install --with acceptance:test' --targets ssh_nodes --inventory inventory.yaml

    - name: Acceptance Tests
      run: |
        bundle exec bolt command run 'cd pdk && CI=true bundle exec rake acceptance:local_parallel' --targets ssh_nodes --inventory inventory.yaml
    
    - name: Tear Down
      if: ${{ always() }}
      run: |
        bundle exec rake 'litmus:tear_down'
